/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'LKS07x_1Motor' 
 * Target:  'Linko_07x_Project' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "lks32mc07x.h"



#endif /* RTE_COMPONENTS_H */
